# Generated by Django 4.2.6 on 2023-10-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('app_slug', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('app_hash', models.CharField(default=None, max_length=255)),
                ('app_name', models.CharField(default=None, max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('file_status', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('ssl_pinned', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='TRUE', max_length=10)),
                ('root_detection', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='TRUE', max_length=10)),
            ],
        ),
    ]
